# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Brewgui3_0.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 659)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.CurrentTime = QtGui.QDateTimeEdit(self.centralwidget)
        self.CurrentTime.setGeometry(QtCore.QRect(20, 560, 194, 33))
        self.CurrentTime.setCalendarPopup(True)
        self.CurrentTime.setObjectName(_fromUtf8("CurrentTime"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 40, 821, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.StatusTab = QtGui.QWidget()
        self.StatusTab.setObjectName(_fromUtf8("StatusTab"))
        self.frame_2 = QtGui.QFrame(self.StatusTab)
        self.frame_2.setGeometry(QtCore.QRect(210, 10, 181, 231))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 67, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.spinMASHset = QtGui.QSpinBox(self.frame_2)
        self.spinMASHset.setGeometry(QtCore.QRect(40, 110, 91, 61))
        self.spinMASHset.setBaseSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(26)
        self.spinMASHset.setFont(font)
        self.spinMASHset.setMaximum(212)
        self.spinMASHset.setObjectName(_fromUtf8("spinMASHset"))
        self.lcdMASHread = QtGui.QLCDNumber(self.frame_2)
        self.lcdMASHread.setGeometry(QtCore.QRect(40, 30, 91, 61))
        self.lcdMASHread.setNumDigits(3)
        self.lcdMASHread.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdMASHread.setProperty("value", 0.0)
        self.lcdMASHread.setObjectName(_fromUtf8("lcdMASHread"))
        self.slideMASHset = QtGui.QSlider(self.frame_2)
        self.slideMASHset.setGeometry(QtCore.QRect(140, 10, 26, 181))
        self.slideMASHset.setMaximum(212)
        self.slideMASHset.setOrientation(QtCore.Qt.Vertical)
        self.slideMASHset.setObjectName(_fromUtf8("slideMASHset"))
        self.checkbox_MashPID = QtGui.QCheckBox(self.frame_2)
        self.checkbox_MashPID.setGeometry(QtCore.QRect(30, 190, 101, 26))
        self.checkbox_MashPID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_MashPID.setObjectName(_fromUtf8("checkbox_MashPID"))
        self.label_36 = QtGui.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(40, 30, 21, 21))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.frame_3 = QtGui.QFrame(self.StatusTab)
        self.frame_3.setGeometry(QtCore.QRect(410, 10, 181, 231))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 67, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spinBOILset = QtGui.QSpinBox(self.frame_3)
        self.spinBOILset.setGeometry(QtCore.QRect(40, 110, 91, 61))
        self.spinBOILset.setBaseSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(26)
        self.spinBOILset.setFont(font)
        self.spinBOILset.setMaximum(212)
        self.spinBOILset.setObjectName(_fromUtf8("spinBOILset"))
        self.lcdBOILread = QtGui.QLCDNumber(self.frame_3)
        self.lcdBOILread.setGeometry(QtCore.QRect(40, 30, 91, 61))
        self.lcdBOILread.setNumDigits(3)
        self.lcdBOILread.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdBOILread.setProperty("value", 0.0)
        self.lcdBOILread.setObjectName(_fromUtf8("lcdBOILread"))
        self.slideBOILset = QtGui.QSlider(self.frame_3)
        self.slideBOILset.setGeometry(QtCore.QRect(140, 10, 26, 181))
        self.slideBOILset.setMaximum(212)
        self.slideBOILset.setOrientation(QtCore.Qt.Vertical)
        self.slideBOILset.setObjectName(_fromUtf8("slideBOILset"))
        self.checkbox_Boilelement_2 = QtGui.QCheckBox(self.frame_3)
        self.checkbox_Boilelement_2.setGeometry(QtCore.QRect(20, 180, 111, 26))
        self.checkbox_Boilelement_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_Boilelement_2.setObjectName(_fromUtf8("checkbox_Boilelement_2"))
        self.checkbox_BoilPID = QtGui.QCheckBox(self.frame_3)
        self.checkbox_BoilPID.setGeometry(QtCore.QRect(30, 200, 101, 26))
        self.checkbox_BoilPID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_BoilPID.setObjectName(_fromUtf8("checkbox_BoilPID"))
        self.label_37 = QtGui.QLabel(self.frame_3)
        self.label_37.setGeometry(QtCore.QRect(40, 30, 21, 21))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.frame = QtGui.QFrame(self.StatusTab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 181, 231))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(6, 0, 61, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(6, 130, 61, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.spinHLTset = QtGui.QSpinBox(self.frame)
        self.spinHLTset.setGeometry(QtCore.QRect(40, 110, 91, 61))
        self.spinHLTset.setBaseSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(26)
        self.spinHLTset.setFont(font)
        self.spinHLTset.setMaximum(212)
        self.spinHLTset.setObjectName(_fromUtf8("spinHLTset"))
        self.slideHLTset = QtGui.QSlider(self.frame)
        self.slideHLTset.setGeometry(QtCore.QRect(140, 10, 26, 181))
        self.slideHLTset.setMaximum(212)
        self.slideHLTset.setOrientation(QtCore.Qt.Vertical)
        self.slideHLTset.setObjectName(_fromUtf8("slideHLTset"))
        self.lcdHLTread = QtGui.QLCDNumber(self.frame)
        self.lcdHLTread.setGeometry(QtCore.QRect(40, 30, 91, 61))
        self.lcdHLTread.setNumDigits(3)
        self.lcdHLTread.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdHLTread.setProperty("value", 0.0)
        self.lcdHLTread.setObjectName(_fromUtf8("lcdHLTread"))
        self.checkbox_HLTelement = QtGui.QCheckBox(self.frame)
        self.checkbox_HLTelement.setGeometry(QtCore.QRect(20, 180, 111, 26))
        self.checkbox_HLTelement.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_HLTelement.setObjectName(_fromUtf8("checkbox_HLTelement"))
        self.checkbox_HLTPID = QtGui.QCheckBox(self.frame)
        self.checkbox_HLTPID.setGeometry(QtCore.QRect(30, 200, 101, 26))
        self.checkbox_HLTPID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_HLTPID.setObjectName(_fromUtf8("checkbox_HLTPID"))
        self.label_35 = QtGui.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(40, 30, 21, 21))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_7 = QtGui.QLabel(self.StatusTab)
        self.label_7.setGeometry(QtCore.QRect(10, 250, 181, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.StatusTab)
        self.label_8.setGeometry(QtCore.QRect(210, 250, 181, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_7 = QtGui.QFrame(self.StatusTab)
        self.frame_7.setGeometry(QtCore.QRect(430, 250, 141, 111))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lcdHEXread = QtGui.QLCDNumber(self.frame_7)
        self.lcdHEXread.setGeometry(QtCore.QRect(20, 30, 91, 61))
        self.lcdHEXread.setNumDigits(3)
        self.lcdHEXread.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdHEXread.setProperty("value", 0.0)
        self.lcdHEXread.setObjectName(_fromUtf8("lcdHEXread"))
        self.label_39 = QtGui.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(20, 30, 21, 21))
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.frame_8 = QtGui.QFrame(self.StatusTab)
        self.frame_8.setGeometry(QtCore.QRect(610, 10, 181, 231))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_19 = QtGui.QLabel(self.frame_8)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(10, 130, 67, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.spinFermset = QtGui.QSpinBox(self.frame_8)
        self.spinFermset.setGeometry(QtCore.QRect(40, 110, 91, 61))
        self.spinFermset.setBaseSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(26)
        self.spinFermset.setFont(font)
        self.spinFermset.setMaximum(212)
        self.spinFermset.setObjectName(_fromUtf8("spinFermset"))
        self.lcdFermread = QtGui.QLCDNumber(self.frame_8)
        self.lcdFermread.setGeometry(QtCore.QRect(40, 30, 91, 61))
        self.lcdFermread.setNumDigits(3)
        self.lcdFermread.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdFermread.setProperty("value", 0.0)
        self.lcdFermread.setObjectName(_fromUtf8("lcdFermread"))
        self.slideFermset = QtGui.QSlider(self.frame_8)
        self.slideFermset.setGeometry(QtCore.QRect(140, 10, 26, 181))
        self.slideFermset.setMaximum(212)
        self.slideFermset.setOrientation(QtCore.Qt.Vertical)
        self.slideFermset.setObjectName(_fromUtf8("slideFermset"))
        self.label_38 = QtGui.QLabel(self.frame_8)
        self.label_38.setGeometry(QtCore.QRect(40, 30, 21, 21))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_25 = QtGui.QLabel(self.StatusTab)
        self.label_25.setGeometry(QtCore.QRect(90, 280, 67, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.StatusTab)
        self.label_26.setGeometry(QtCore.QRect(90, 310, 67, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.StatusTab)
        self.label_27.setGeometry(QtCore.QRect(90, 340, 91, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.layoutWidget = QtGui.QWidget(self.StatusTab)
        #changed 21 to 51
        self.layoutWidget.setGeometry(QtCore.QRect(250, 277, 51, 181))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkbox_BlackValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_BlackValve.setText(_fromUtf8(""))
        self.checkbox_BlackValve.setCheckable(True)
        self.checkbox_BlackValve.setChecked(True)
        self.checkbox_BlackValve.setObjectName(_fromUtf8("checkbox_BlackValve"))
        self.verticalLayout_2.addWidget(self.checkbox_BlackValve)
        self.checkbox_RedValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_RedValve.setText(_fromUtf8(""))
        self.checkbox_RedValve.setCheckable(True)
        self.checkbox_RedValve.setChecked(True)
        self.checkbox_RedValve.setObjectName(_fromUtf8("checkbox_RedValve"))
        self.verticalLayout_2.addWidget(self.checkbox_RedValve)
        self.checkbox_OrangeValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_OrangeValve.setText(_fromUtf8(""))
        self.checkbox_OrangeValve.setCheckable(True)
        self.checkbox_OrangeValve.setChecked(True)
        self.checkbox_OrangeValve.setObjectName(_fromUtf8("checkbox_OrangeValve"))
        self.verticalLayout_2.addWidget(self.checkbox_OrangeValve)
        self.checkbox_YellowValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_YellowValve.setText(_fromUtf8(""))
        self.checkbox_YellowValve.setCheckable(True)
        self.checkbox_YellowValve.setChecked(True)
        self.checkbox_YellowValve.setObjectName(_fromUtf8("checkbox_YellowValve"))
        self.verticalLayout_2.addWidget(self.checkbox_YellowValve)
        self.checkbox_GreenValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_GreenValve.setText(_fromUtf8(""))
        self.checkbox_GreenValve.setCheckable(True)
        self.checkbox_GreenValve.setChecked(True)
        self.checkbox_GreenValve.setObjectName(_fromUtf8("checkbox_GreenValve"))
        self.verticalLayout_2.addWidget(self.checkbox_GreenValve)
        self.checkbox_BlueValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_BlueValve.setText(_fromUtf8(""))
        self.checkbox_BlueValve.setCheckable(True)
        self.checkbox_BlueValve.setChecked(True)
        self.checkbox_BlueValve.setObjectName(_fromUtf8("checkbox_BlueValve"))
        self.verticalLayout_2.addWidget(self.checkbox_BlueValve)
        self.checkbox_PurpleValve = QtGui.QCheckBox(self.layoutWidget)
        self.checkbox_PurpleValve.setText(_fromUtf8(""))
        self.checkbox_PurpleValve.setCheckable(True)
        self.checkbox_PurpleValve.setChecked(True)
        self.checkbox_PurpleValve.setObjectName(_fromUtf8("checkbox_PurpleValve"))
        self.verticalLayout_2.addWidget(self.checkbox_PurpleValve)
        self.layoutWidget1 = QtGui.QWidget(self.StatusTab)
        #changed 21 to 51
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 280, 51, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkbox_HLTpump = QtGui.QCheckBox(self.layoutWidget1)
        self.checkbox_HLTpump.setText(_fromUtf8(""))
        self.checkbox_HLTpump.setCheckable(True)
        self.checkbox_HLTpump.setChecked(True)
        self.checkbox_HLTpump.setObjectName(_fromUtf8("checkbox_HLTpump"))
        self.verticalLayout.addWidget(self.checkbox_HLTpump)
        self.checkbox_MashPump2 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkbox_MashPump2.setText(_fromUtf8(""))
        self.checkbox_MashPump2.setCheckable(True)
        self.checkbox_MashPump2.setChecked(True)
        self.checkbox_MashPump2.setObjectName(_fromUtf8("checkbox_MashPump2"))
        self.verticalLayout.addWidget(self.checkbox_MashPump2)
        self.checkbox_Pump1 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkbox_Pump1.setText(_fromUtf8(""))
        self.checkbox_Pump1.setCheckable(True)
        self.checkbox_Pump1.setChecked(True)
        self.checkbox_Pump1.setObjectName(_fromUtf8("checkbox_Pump1"))
        self.verticalLayout.addWidget(self.checkbox_Pump1)
        self.layoutWidget2 = QtGui.QWidget(self.StatusTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 274, 74, 185))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_28 = QtGui.QLabel(self.layoutWidget2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_3.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_3.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.layoutWidget2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_3.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.layoutWidget2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.layoutWidget2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_3.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.layoutWidget2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_3.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.layoutWidget2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_3.addWidget(self.label_34)
        self.timeEdit_currentstep = QtGui.QTimeEdit(self.StatusTab)
        self.timeEdit_currentstep.setGeometry(QtCore.QRect(620, 330, 118, 33))
        self.timeEdit_currentstep.setReadOnly(True)
        self.timeEdit_currentstep.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit_currentstep.setObjectName(_fromUtf8("timeEdit_currentstep"))
        self.pushButton_start = QtGui.QPushButton(self.StatusTab)
        self.pushButton_start.setGeometry(QtCore.QRect(620, 370, 41, 31))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        
        self.pushButton_pause = QtGui.QPushButton(self.StatusTab)
        self.pushButton_pause.setGeometry(QtCore.QRect(670, 370, 51, 31))
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.pushButton_next = QtGui.QPushButton(self.StatusTab)
        self.pushButton_next.setGeometry(QtCore.QRect(730, 370, 41, 31))
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.label_9 = QtGui.QLabel(self.StatusTab)
        self.label_9.setGeometry(QtCore.QRect(620, 260, 101, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_curentstep = QtGui.QComboBox(self.StatusTab)
        self.comboBox_curentstep.setGeometry(QtCore.QRect(620, 290, 181, 31))
        self.comboBox_curentstep.setObjectName(_fromUtf8("comboBox_curentstep"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.timeEdit_currentstep.raise_()
        self.pushButton_start.raise_()
        self.pushButton_pause.raise_()
        self.pushButton_next.raise_()
        self.label_9.raise_()
        self.comboBox_curentstep.raise_()
        self.tabWidget.addTab(self.StatusTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 791, 371))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 15, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 30, 471, 381))
        self.tableWidget_2.setRowCount(12)
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(105)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(530, 320, 101, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 320, 101, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(580, 130, 191, 31))
        self.comboBox.setModelColumn(-1)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(530, 50, 91, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_stepnumber = QtGui.QLabel(self.tab)
        self.label_stepnumber.setGeometry(QtCore.QRect(620, 50, 67, 21))
        self.label_stepnumber.setObjectName(_fromUtf8("label_stepnumber"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(530, 130, 67, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(530, 170, 67, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(580, 170, 91, 33))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(530, 210, 67, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.spinBox_2 = QtGui.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(580, 210, 91, 33))
        self.spinBox_2.setMinimum(32)
        self.spinBox_2.setMaximum(212)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(530, 90, 67, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(580, 90, 191, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_Recipe = QtGui.QAction(MainWindow)
        self.actionNew_Recipe.setObjectName(_fromUtf8("actionNew_Recipe"))
        self.actionSave_Recipe = QtGui.QAction(MainWindow)
        self.actionSave_Recipe.setObjectName(_fromUtf8("actionSave_Recipe"))
        self.actionOpen_Recipe = QtGui.QAction(MainWindow)
        self.actionOpen_Recipe.setObjectName(_fromUtf8("actionOpen_Recipe"))
        self.menuFile.addAction(self.actionNew_Recipe)
        self.menuFile.addAction(self.actionOpen_Recipe)
        self.menuFile.addAction(self.actionSave_Recipe)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.slideMASHset, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinMASHset.setValue)
        QtCore.QObject.connect(self.spinMASHset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slideMASHset.setValue)
        QtCore.QObject.connect(self.spinHLTset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slideHLTset.setValue)
        QtCore.QObject.connect(self.slideBOILset, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBOILset.setValue)
        QtCore.QObject.connect(self.slideHLTset, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinHLTset.setValue)
        QtCore.QObject.connect(self.spinBOILset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slideBOILset.setValue)
        QtCore.QObject.connect(self.slideFermset, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinFermset.setValue)
        QtCore.QObject.connect(self.spinFermset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slideFermset.setValue)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), self.comboBox.update)
        QtCore.QObject.connect(self.tableWidget_2, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), self.label_stepnumber.setNum)
        self.connect(self.pushButton_start, QtCore.SIGNAL("released()"), self.test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.CurrentTime.setDisplayFormat(_translate("MainWindow", "M/d/yy h:mm AP", None))
        self.label_2.setText(_translate("MainWindow", "Mash Tun", None))
        self.label_5.setText(_translate("MainWindow", "Set", None))
        self.checkbox_MashPID.setText(_translate("MainWindow", "PID Select", None))
        self.label_36.setText(_translate("MainWindow", "°F", None))
        self.label_3.setText(_translate("MainWindow", "Boil", None))
        self.label_6.setText(_translate("MainWindow", "Set", None))
        self.checkbox_Boilelement_2.setText(_translate("MainWindow", "Element On", None))
        self.checkbox_BoilPID.setText(_translate("MainWindow", "PID Select", None))
        self.label_37.setText(_translate("MainWindow", "°F", None))
        self.label.setText(_translate("MainWindow", "HLT", None))
        self.label_4.setText(_translate("MainWindow", "Set", None))
        self.checkbox_HLTelement.setText(_translate("MainWindow", "Element On", None))
        self.checkbox_HLTPID.setText(_translate("MainWindow", "PID Select", None))
        self.label_35.setText(_translate("MainWindow", "°F", None))
        self.label_7.setText(_translate("MainWindow", "Pumps", None))
        self.label_8.setText(_translate("MainWindow", "Valves", None))
        self.label_17.setText(_translate("MainWindow", "HEX Output", None))
        self.label_39.setText(_translate("MainWindow", "°F", None))
        self.label_19.setText(_translate("MainWindow", "Fermenter", None))
        self.label_20.setText(_translate("MainWindow", "Set", None))
        self.label_38.setText(_translate("MainWindow", "°F", None))
        self.label_25.setText(_translate("MainWindow", "HLT", None))
        self.label_26.setText(_translate("MainWindow", "Mash", None))
        self.label_27.setText(_translate("MainWindow", "Boil Kettle", None))
        self.label_28.setText(_translate("MainWindow", "Black", None))
        self.label_29.setText(_translate("MainWindow", "Red", None))
        self.label_30.setText(_translate("MainWindow", "Orange", None))
        self.label_31.setText(_translate("MainWindow", "Yellow", None))
        self.label_32.setText(_translate("MainWindow", "Green", None))
        self.label_33.setText(_translate("MainWindow", "Blue", None))
        self.label_34.setText(_translate("MainWindow", "Purple", None))
        self.timeEdit_currentstep.setDisplayFormat(_translate("MainWindow", "h:mm:ss", None))
        self.pushButton_start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_next.setText(_translate("MainWindow", "Next", None))
        self.label_9.setText(_translate("MainWindow", "Current Step", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StatusTab), _translate("MainWindow", "Status", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Step", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pump 1 H", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pump 2 M", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pump 3 B", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Black", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Red", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Orange", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Yellow", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Green", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Blue", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Purple", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "White", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "HLT PID", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "MASH PID", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "BOIL PID", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "SELECT BOIL=1", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Fill", None))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Heat Strike", None))
        item = self.tableWidget.item(1, 12)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Strike", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(2, 13)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Refill", None))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(3, 12)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Reheat", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(4, 12)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Mash", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(5, 13)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Mash Out", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(6, 13)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Sparge", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(7, 12)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "Boil", None))
        item = self.tableWidget.item(8, 14)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(8, 15)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "Whirlpool", None))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(9, 14)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(9, 15)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "Chill (fill clean)", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(10, 9)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(10, 14)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(10, 15)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "Chill (drain)", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(11, 14)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(11, 15)
        item.setText(_translate("MainWindow", "1", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "State Table", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "State", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temp", None))
        self.pushButton.setText(_translate("MainWindow", "Add Row", None))
        self.pushButton_2.setText(_translate("MainWindow", "Delete Row", None))
        self.label_18.setText(_translate("MainWindow", "Recipe Step:", None))
        self.label_stepnumber.setText(_translate("MainWindow", "1", None))
        self.label_21.setText(_translate("MainWindow", "State:", None))
        self.label_22.setText(_translate("MainWindow", "Time:", None))
        self.spinBox.setSpecialValueText(_translate("MainWindow", "Manual", None))
        self.label_23.setText(_translate("MainWindow", "Temp:", None))
        self.spinBox_2.setSpecialValueText(_translate("MainWindow", "None", None))
        self.label_24.setText(_translate("MainWindow", "Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Recipe", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionNew_Recipe.setText(_translate("MainWindow", "New Recipe", None))
        self.actionSave_Recipe.setText(_translate("MainWindow", "Save Recipe", None))
        self.actionOpen_Recipe.setText(_translate("MainWindow", "Open Recipe", None))

